#ifndef _FILLING_SM_CONFIG_H_
#define _FILLING_SM_CONFIG_H_

// NOTE: Pressures in bar
//       weights in kg
//       temperatures in ºC

#define SAFE_PAUSE_TARGET_N2O_TANK_P  50
#define SAFE_PAUSE_TRIGGER_N2O_TANK_P 52

#define FILLING_COPV_TARGET_N2_TANK_P 200

#define PRE_PRESSURIZING_TARGET_N2O_TANK_P  5
#define PRE_PRESSURIZING_TRIGGER_N2O_TANK_P 7

#define FILLING_N2O_TARGET_N2O_TANK_P  35
#define FILLING_N2O_TARGET_N2O_TANK_W  7
#define FILLING_N2O_TRIGGER_N2O_TANK_P 38
#define FILLING_N2O_TRIGGER_N2O_TANK_T 2

#define POST_PRESSURIZING_TARGET_N2O_TANK_P  50
#define POST_PRESSURIZING_TRIGGER_N2O_TANK_P 52

#endif // _FILLING_SM_CONFIG_H_
