---
manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: lora-net
      url-base: https://github.com/Lora-net

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import: true

    # - name: LBM_Zephyr
    #   remote: lora-net
    #   revision: master
    #   import: true
